name: libsql_dart
description: Flutter client library for libSQL.
version: 0.1.0
repository: https://github.com/garysm/libsql_dart/tree/main
issue_tracker: https://github.com/garysm/libsql_dart/issues

environment:
  sdk: ^3.1.2

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
