rust_input: [src/api.rs]
dart_output: [../lib/src/bridge_generated.dart]
wasm: true
dart_decl_output: ../dart/lib/bridge_definitions.dart
dart_format_line_length: 120
dart_enums_style: true
dart3: true
c_output: [c_output_path/c_output.h]
ios_output: [../../flutter_libsql_dart/ios/Classes/frb.h]
macos_c_output_dir: [../../flutter_libsql_dart/macos/Classes/]
extra_c_output_path:
  - c_output_path_extra/
class_name: [LibSQL]
# dump: []
