[package]
name = "libsql_dart"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
doc = false

[build-dependencies]
cbindgen = "0.24.0"

[dependencies]
lazy_static = "1.4.0"
libsql = { git = "https://github.com/libsql/libsql/", rev = "523be13c79e465f452354c3400334269580aad8f" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }