[package]
name = "libsql_dart"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]


[dependencies]
tracing-subscriber = "0.3"
libsql = { git = "https://github.com/libsql/libsql/", rev = "523be13c79e465f452354c3400334269580aad8f" }
log = "0.4.20"
once_cell = "1.18.0"
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }